#!/usr/bin/env bash

clear && \
ldc main.d lexer.d ast.d parser.d generator.d && \
./main test.bs && \
#nasm -f elf64 output.asm && \
basm output.asm && \
ld output.o && \
./a.out; \
OUTPUT="$?" && \
echo "output: $OUTPUT"
