#!/usr/bin/env bash

clear && \
echo && echo && echo && echo && echo && echo && echo && echo && echo && \
echo && echo && echo && echo && echo && echo && echo && echo && echo && \
echo && echo && echo && echo && echo && echo && echo && echo && echo && \

make && \

bin/bshift -v "${1}" && \

./a.out; \
OUTPUT="$?" && \
echo "execution output --------------------------------------------------" && \
echo && \
echo "$OUTPUT"
